import Table from "@/components/atoms/Table/Table";
import Header from "@/components/molecules/Header/Header";
import { Box } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Box component="main" sx={{ p: 3 }}>
        <Table />
      </Box>
    </>
  );
}
